version: "3"
services:

    mysql:
        image: beercan1989/arm-mysql:latest
        hostname: mysql
        container_name: mysql
        restart: always
        volumes:
            - /mnt/wd-passport/mysql:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}

    adminer:
        image: adminer:latest
        hostname: adminer
        container_name: adminer
        restart: always
        ports:
            - 8084:80

    redis:
        image: redis:latest
        hostname: redis
        container_name: redis
        restart: always

    nextcloud:
        image: nextcloud:latest
        hostname: nextcloud
        container_name: nextcloud
        restart: always
        depends_on:
            - mysql
            - redis
        ports:
            - 8080:80
        volumes:
            - /mnt/wd-passport/nextcloud:/var/www/html
        environment:
            MYSQL_HOST: mysql
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            REDIS_HOST: redis
            TRUSTED_PROXIES: reverse-proxy
            NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.${DOMAIN_NAME}

    bitwarden:
        image : bitwardenrs/server:raspberry
        hostname: bitwarden
        container_name: bitwarden
        restart: always
        volumes:
            - /mnt/wd-passport/bitwarden:/data
        ports:
            - 8081:80
            - 3012:3012

    blog:
        image: wordpress:latest
        hostname: blog
        container_name: blog
        restart: always
        depends_on: 
            - mysql
        ports:
            - 8082:80
        volumes:
            - /mnt/wd-passport/wordpress:/var/www/html
        environment: 
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

    pihole:
        image: pihole/pihole:latest
        hostname: pihole
        container_name: pihole
        restart: always
        volumes:
            - ./pihole:/etc/pihole
            - ./pihole/dnsmasq.d:/etc/dnsmasq.d
        ports:
            - 53:53/tcp
            - 53:53/udp
            - 67:67/udp
            - 8083:80
        environment:
            TZ: America/New York
            WEBPASSWORD: ${PIHOLE_PASSWORD}
            VIRTUAL_HOST: pihole.${DOMAIN_NAME}
        dns:
            - 127.0.0.1
            - 1.1.1.1
        cap_add:
            - NET_ADMIN

    #reverse-proxy:
    #    image: nginx:latest
    #    hostname: reverse-proxy
    #    container_name: reverse-proxy
    #    restart: always
    #    depends_on: 
    #        - nextcloud
    #        - bitwarden
    #        - blog
    #        - pihole
    #        - adminer
    #    volumes:
    #        - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    #        - ./reverse-proxy/conf.d:/etc/nginx/conf.d
    #    ports: 
    #        - 80:80
    #        - 443:443