version: "3"
services:

    postgres:
        image: postgres:latest
        hostname: postgres
        container_name: postgres
        restart: always
        volumes:
            - postgres:/var/lib/postgresql/data/pgdata
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata

    redis:
        image: redis:latest
        hostname: redis
        container_name: redis
        restart: always

    nextcloud:
        image: nextcloud:latest
        hostname: nextcloud
        container_name: nextcloud
        restart: always
        depends_on:
            - postgres
            - redis
        ports:
            - 8080:80
        volumes:
            - nextcloud:/var/www/html
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            REDIS_HOST: redis

    bitwarden:
        image : bitwardenrs/server:raspberry
        hostname: bitwarden
        container_name: bitwarden
        restart: always
        ports:
            - 8081:80
        volumes:
            - bitwarden:/data

    drupal:
        image: drupal:latest
        hostname: drupal
        container_name: drupal
        restart: always
        depends_on: 
            - postgres
        ports:
            - 8082:80
        volumes:
            - drupal:/var/www/html

    pihole:
        image: pihole/pihole:latest
        hostname: pihole
        container_name: pihole
        restart: always
        volumes:
            - pihole:/etc/pihole
            - pihole-dnsmasq:/etc/dnsmasq.d/
        ports:
            - 53:53/tcp
            - 53:53/udp
            - 67:67/udp
            - 8083:80
        environment:
            TZ: America/New York
            WEBPASSWORD: ${PIHOLE_PASSWORD}
        dns:
            - 127.0.0.1
            - 1.1.1.1
        cap_add:
            - NET_ADMIN

volumes:    
    postgres:
    nextcloud:
    bitwarden:
    drupal:
    pihole:
    pihole-dnsmasq: